[ssh]
ssh_host = "xx.xx.xx.xx"
ssh_port = 22
ssh_user = "root"
ssh_pkey = "./privateKey/id_rsa"
ssh_pass = "xxxxx"

[ssh_bind]
# 远程绑定地址(建立SSH通道后)
remote_bind_addr = "127.0.0.1"

# 本地绑定地址(建立SSH通道后)
local_bind_addr = "0.0.0.0"

# 绑定端口(建立SSH通道后,指向数据库端口, port1:port2,其中port1代表本地端口，port2代表远程端口)
bind_port = [
            [12345, 12345],
            [12012, 2012],
            [13013, 13013]
]
